
version: 2
models:
  - name: composed_16651147367555242
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
