
version: 2
models:
  - name: redeployment_1665114735783859
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
